models:
  - name: stg_transactions
    columns:
      - name: transaction_id
        tests:
          - not_null
          - unique

      - name: account_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_accounts')
              field: account_id

  - name: dim_accounts
    columns:
      - name: account_id
        tests:
          - not_null
          - unique

      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_customers')
              field: customer_id

  - name: fct_transactions
    columns:
      - name: transaction_id
        tests:
          - not_null
          - unique

      - name: account_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_accounts')
              field: account_id

  - name: dim_customers
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique